// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NiceTry")]
[assembly: AssemblyProductAttribute("NiceTry")]
[assembly: AssemblyDescriptionAttribute("A monoid")]
[assembly: AssemblyVersionAttribute("4.1.0")]
[assembly: AssemblyFileVersionAttribute("4.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "4.1.0";
        internal const string InformationalVersion = "4.1.0";
    }
}
