// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NiceTry")]
[assembly: AssemblyDescriptionAttribute("A functional wrapper type for the classic try/catch statement")]
[assembly: GuidAttribute("d9712c70-9a11-43b9-b9b4-10b4036ea8f2")]
[assembly: AssemblyProductAttribute("NiceTry")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.0";
    }
}
